# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:

  goadlc:
    taskfile: ./goadlc/Taskfile.local.yml
    dir: ./goadlc

  gen_prim_texpr:
    taskfile: ./gen_prim_texpr/Taskfile.local.yml
    dir: ./gen_prim_texpr

  tests:
    taskfile: ./tests/Taskfile.local.yml
    dir: ./tests

tasks:

  gen:
    cmds:
      - task gen_prim_texpr:gen_texpr
      - task goadlc:gen_adlast
      - task goadlc:gen_goadlc
      - task goadlc:gen_stdlib
      - task tests:gen_exer
      - task tests:gen_api

  test:
    cmds:
      - task tests:test