// Code generated by goadlc - DO NOT EDIT.
package govisitor

import (
	"github.com/adl-lang/adl-go/goadlc/internal/cli/gomod"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/loader"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/root"
)

type GoVisitor struct {
	_GoVisitor
}

type _GoVisitor struct {
	Root                *root.Root         `json:"-"`
	Loader              *loader.LoadResult `json:"-"`
	GoMod               *gomod.GoModResult `json:"-"`
	NoGoFmt             bool               `json:"NoGoFmt"`
	GoAdlPath           string             `json:"GoAdlPath"`
	Modules             []string           `json:"Modules"`
	SkipTypeCheckMethod bool               `json:"SkipTypeCheckMethod"`
	Outputdir           string             `json:"Outputdir"`
}

func MakeAll_GoVisitor(
	root *root.Root,
	loader *loader.LoadResult,
	gomod *gomod.GoModResult,
	nogofmt bool,
	goadlpath string,
	modules []string,
	skiptypecheckmethod bool,
	outputdir string,
) GoVisitor {
	return GoVisitor{
		_GoVisitor{
			Root:                root,
			Loader:              loader,
			GoMod:               gomod,
			NoGoFmt:             nogofmt,
			GoAdlPath:           goadlpath,
			Modules:             modules,
			SkipTypeCheckMethod: skiptypecheckmethod,
			Outputdir:           outputdir,
		},
	}
}

func Make_GoVisitor(
	outputdir string,
) GoVisitor {
	ret := GoVisitor{
		_GoVisitor{
			Root:                ((*GoVisitor)(nil)).Default_root(),
			Loader:              ((*GoVisitor)(nil)).Default_loader(),
			GoMod:               ((*GoVisitor)(nil)).Default_goMod(),
			NoGoFmt:             ((*GoVisitor)(nil)).Default_NoGoFmt(),
			GoAdlPath:           ((*GoVisitor)(nil)).Default_GoAdlPath(),
			Modules:             ((*GoVisitor)(nil)).Default_Modules(),
			SkipTypeCheckMethod: ((*GoVisitor)(nil)).Default_SkipTypeCheckMethod(),
			Outputdir:           outputdir,
		},
	}
	return ret
}

func (*GoVisitor) Default_root() *root.Root {
	return nil
}
func (*GoVisitor) Default_loader() *loader.LoadResult {
	return nil
}
func (*GoVisitor) Default_goMod() *gomod.GoModResult {
	return nil
}
func (*GoVisitor) Default_NoGoFmt() bool {
	return false
}
func (*GoVisitor) Default_GoAdlPath() string {
	return "github.com/adl-lang/adl-go/adl"
}
func (*GoVisitor) Default_Modules() []string {
	return []string{}
}
func (*GoVisitor) Default_SkipTypeCheckMethod() bool {
	return false
}
