// Code generated by goadlc - DO NOT EDIT.
package gengo

import (
	"github.com/adl-lang/adl-go/goadlc/internal/cli/goapi"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/gomod"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/gotypes"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/govisitor"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/loader"
	"github.com/adl-lang/adl-go/goadlc/internal/cli/root"
)

type GenGo struct {
	_GenGo
}

type _GenGo struct {
	Root      *root.Root           `json:"-"`
	Loader    *loader.Loader       `json:"Loader"`
	Mod       *gomod.GoModule      `json:"Mod"`
	ChangePWD string               `json:"ChangePWD"`
	GoTypes   *gotypes.GoTypes     `json:"GoTypes"`
	GoApis    *[]goapi.GoApi       `json:"GoApis"`
	GoVisitor *govisitor.GoVisitor `json:"GoVisitor"`
}

func MakeAll_GenGo(
	root *root.Root,
	loader *loader.Loader,
	mod *gomod.GoModule,
	changepwd string,
	gotypes *gotypes.GoTypes,
	goapis *[]goapi.GoApi,
	govisitor *govisitor.GoVisitor,
) GenGo {
	return GenGo{
		_GenGo{
			Root:      root,
			Loader:    loader,
			Mod:       mod,
			ChangePWD: changepwd,
			GoTypes:   gotypes,
			GoApis:    goapis,
			GoVisitor: govisitor,
		},
	}
}

func Make_GenGo(
	loader *loader.Loader,
	mod *gomod.GoModule,
	gotypes *gotypes.GoTypes,
) GenGo {
	ret := GenGo{
		_GenGo{
			Root:      ((*GenGo)(nil)).Default_root(),
			Loader:    loader,
			Mod:       mod,
			ChangePWD: ((*GenGo)(nil)).Default_ChangePWD(),
			GoTypes:   gotypes,
			GoApis:    ((*GenGo)(nil)).Default_GoApis(),
			GoVisitor: ((*GenGo)(nil)).Default_GoVisitor(),
		},
	}
	return ret
}

func (*GenGo) Default_root() *root.Root {
	return nil
}
func (*GenGo) Default_ChangePWD() string {
	return ""
}
func (*GenGo) Default_GoApis() *[]goapi.GoApi {
	return nil
}
func (*GenGo) Default_GoVisitor() *govisitor.GoVisitor {
	return nil
}
